from sqlalchemy import Column, String, Boolean, Float
from sqlalchemy.dialects.postgresql import ARRAY
from src.zoho_nigeria_inventory.db.database import Base

class Item(Base):
    __tablename__ = "items"
    __table_args__ = {"schema": "zoho_nigeria_inventory"}  # Explicit schema


    item_id = Column(String, primary_key=True, index=True)
    name = Column(String)
    item_name = Column(String)
    category_id = Column(String)
    category_name = Column(String)
    unit = Column(String)
    status = Column(String)
    source = Column(String)
    is_combo_product = Column(Boolean)
    is_linked_with_zohocrm = Column(Boolean)
    zcrm_product_id = Column(String)
    description = Column(String)
    brand = Column(String)
    manufacturer = Column(String)
    rate = Column(Float)
    tax_id = Column(String)
    tax_name = Column(String)
    tax_percentage = Column(Float)
    purchase_account_id = Column(String)
    purchase_account_name = Column(String)
    account_id = Column(String)
    account_name = Column(String)
    purchase_description = Column(String)
    purchase_rate = Column(Float)
    can_be_sold = Column(Boolean)
    can_be_purchased = Column(Boolean)
    track_inventory = Column(Boolean)
    item_type = Column(String)
    product_type = Column(String)
    has_attachment = Column(Boolean)
    is_returnable = Column(Boolean)
    sku = Column(String)
    upc = Column(String)
    ean = Column(String)
    isbn = Column(String)
    part_number = Column(String)
    track_serial_number = Column(Boolean)
    track_batch_number = Column(Boolean)
    is_storage_location_enabled = Column(Boolean)
    image_name = Column(String)
    image_type = Column(String)
    image_document_id = Column(String)
    created_time = Column(String)
    last_modified_time = Column(String)
    show_in_storefront = Column(Boolean)
    cf_warranty_period = Column(String)
    cf_warranty_period_unformatted = Column(String)
    length = Column(Float)
    width = Column(Float)
    height = Column(Float)
    weight = Column(Float)
    weight_unit = Column(String)
    dimension_unit = Column(String)
    tags = Column(ARRAY(String))
    stock_on_hand = Column(Float)
    available_stock = Column(Float)
    actual_available_stock = Column(Float)
    reorder_level = Column(Float)
