from sqlalchemy import Column, String, Boolean, Float
from sqlalchemy.dialects.postgresql import ARRAY
from src.zoho_nigeria_inventory.db.database import Base


class CompositeItem(Base):
    __tablename__ = "composite_items"
    __table_args__ = {"schema": "zoho_nigeria_inventory"}  # Explicit schema

    composite_item_id = Column(String, primary_key=True, index=True)
    name = Column(String)
    #item_name = Column(String)
    category_id = Column(String)
    category_name = Column(String)
    unit = Column(String)
    status = Column(String)
    source = Column(String)
    is_linked_with_zohocrm = Column(Boolean)
    #zcrm_product_id = Column(String)
    description = Column(String)
    brand = Column(String)
    manufacturer = Column(String)
    rate = Column(Float)
    tax_id = Column(String)
    tax_name = Column(String)
    tax_percentage = Column(Float)
    #purchase_account_id = Column(String)
    #purchase_account_name = Column(String)
    purchase_description = Column(String)
    purchase_rate = Column(Float)
    is_combo_product = Column(Boolean)
    assembly_type = Column(String)
    combo_type = Column(String)
    can_be_sold = Column(Boolean)
    can_be_purchased = Column(Boolean)
    track_inventory = Column(Boolean)
    item_type = Column(String)
    is_returnable = Column(Boolean)
    stock_on_hand = Column(Float)
    available_stock = Column(Float)
    actual_available_stock = Column(Float)
    track_serial_number = Column(Boolean)
    minimum_order_quantity = Column(Float)
    maximum_order_quantity = Column(Float)
    sku = Column(String)
    upc = Column(String)
    ean = Column(String)
    isbn = Column(String)
    part_number = Column(String)
    reorder_level = Column(Float)
    image_name = Column(String)
    image_type = Column(String)
    image_document_id = Column(String)
    created_time = Column(String)
    last_modified_time = Column(String)