version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      DATABASE_URL: DATABASE_URL
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  fastapi:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - .:/fastapi-app

volumes:
  postgres_data:

networks:
  app-network:
